### ISSUE TITLE
aanmaken nieuw conceptscheme

### ISSUE THREAD

**Issue by bertvannuffelen** [OnroerendErfgoed/atramhasis#474] opened 2019-04-18 07:29 UTC
Beste,

ik heb de atramhasis demo gestart en zocht daarin de mogelijkheid om een nieuw conceptscheme aan te maken. Maar dat is blijkbaar niet mogelijk via de admin interface. Als ik de docs (https://atramhasis.readthedocs.io/en/latest/customisation.html) goed lees dan moet dat manueel via code configuratie gebeuren, voordat je de editor opstart. klopt dat?

mvg,

Bert

**Comment by bertvannuffelen** [comment] 2019-04-18 09:16
I found the approach using file_import to load external conceptschemes, but also here some (re)configuration is required.

**Comment by koenedaele** [comment] 2019-04-21 20:39
Yes, that is by design. We found there was too much configuring that needed to be done in code (uri generators and such) that there was no quick fix for creating conceptschemes through the interface. There are probably soms possible paths we could follow, but once you want to do some advanced configuring it becomes more complicated.

**Comment by koenedaele** [comment] 2022-10-03 20:47
Closing this as a duplicate of #724

**Closed by koenedaele** 2022-10-03 20:47 UTC
