### ISSUE TITLE
InvalidRequestError

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/atramhasis#304] opened 2016-06-06 08:46 UTC
Not sure if this is related with one of the existing issues but I get following error from time to time when opening a concept(scheme) in the public frontend.

```
  File "/home/maarten/development/work/OE/atramhasis/atramhasis/audit.py", line 59, in advice
    response = fn(parent_object, *args, **kw)
  File "/home/maarten/development/work/OE/atramhasis/atramhasis/views/views.py", line 135, in concept_view
    for not_shown in ['external', 'hidden']])
  File "/home/maarten/Envs/atramhasis/src/skosprovider-sqlalchemy/skosprovider_sqlalchemy/providers.py", line 98, in concept_scheme
    return self._get_concept_scheme()
  File "/home/maarten/Envs/atramhasis/src/skosprovider-sqlalchemy/skosprovider_sqlalchemy/utils.py", line 260, in go
    parent_object.session.rollback()
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 765, in rollback
    self.transaction.rollback()
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 419, in rollback
    transaction._rollback_impl()
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 449, in _rollback_impl
    t[1].rollback()
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1563, in rollback
    self._do_rollback()
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1601, in _do_rollback
    self.connection._rollback_impl()
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 670, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 668, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139925982775040 and this is thread id 139925999560448
```

**Comment by koenedaele** [comment] 2016-06-06 09:12
@BartSaelen Can you look into this when you have some time?

**Comment by taeymma** [comment] 2016-06-06 11:14
```
2016-06-06 13:13:47,281 ERROR [atramhasis.views.exception_views][waitress] This Session's transaction has been rolled back by a nested rollback() call.  To begin a new transaction, issue Session.rollback() first.
Traceback (most recent call last):
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 123, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/maarten/development/work/OE/atramhasis/atramhasis/views/views.py", line 77, in home_view
    for not_shown in ['external', 'hidden']])
  File "/home/maarten/Envs/atramhasis/src/skosprovider-sqlalchemy/skosprovider_sqlalchemy/providers.py", line 98, in concept_scheme
    return self._get_concept_scheme()
  File "/home/maarten/Envs/atramhasis/src/skosprovider-sqlalchemy/skosprovider_sqlalchemy/utils.py", line 255, in go
    parent_object.session.begin(subtransactions=True)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 725, in begin
    nested=nested)
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 235, in _begin
    self._assert_active()
  File "/home/maarten/Envs/atramhasis/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 218, in _assert_active
    "This Session's transaction has been rolled back "
InvalidRequestError: This Session's transaction has been rolled back by a nested rollback() call.  To begin a new transaction, issue Session.rollback() first.
```

**Comment by BartSaelen** [comment] 2016-07-27 07:38
How do I reproduce this?

**Comment by taeymma** [comment] 2016-07-28 09:47
This seems to appear when refreshing the page when its not completely loaded.

**Comment by BartSaelen** [comment] 2016-08-02 14:43
This issue only occurs with sqlite, not with postgresql. In my opinion this is a non critical issue. Sqlite is only intended for testing purposes. For high availability scenarios, I recommend postgresql.

I haven't found a suitable solution for sqlite yet.

**Comment by koenedaele** [comment] 2021-11-25 10:32
Closing this because it seems old and might no longer be an issue.

**Closed by koenedaele** 2021-11-25 10:32 UTC
Labels: bug, help wanted
